# ESCENARIO
w_w: 300  # ancho
w_h: 300  # alto
obj_r: 25  # radio del objetivo
obj_x: 50  # coordenadas fijas de objetivo (-1: aleatorio)
obj_y: 50  # coordenadas fijas de objetivo (-1: aleatorio)
# OVEJAS
N: 10  # numero de ovejas
r_s: 65.0  # radio de repulsion del pastor
r_a: 2.0  # radio de repulsion de otras ovejas
h: 0.5  # coeficiente de inercia
c: 1.05  # coeficiente de cohesion
rho_a: 2.0  # fuerza de repulsion (oveja-oveja)
rho_s: 1.0  # fuerza de repulsion (pastor-oveja)
e: 0.3  # ruido angular (componente estocastica)
delta: 1.0  # distancia por paso
n_neigh: 4  # numero de vecinos para cohesion
r_walk: 0.05  # probabilidad de random walk
# PASTOR
N_pastores: 1
p_delta: 1.5  # distancia por paso
model: "NN"  # modelo de comportamiento del pastor (followMouse | NN)
min_w: -15  # valor minimo de peso
max_w: 16  # valor maximo de peso
pers_ovejas: 5  # ovejas percibidas por el pastor
pers_pastores: 0  # otros pastores percibidos por el pastor
hidden_lay_1: 128  # neuronas de la primer capa oculta
hidden_lay_2: 64  # neuronas de la segunda capa oculta
# ENTRENAMIENTO
max_steps_ini: 200  # numero maximo de pasos por simulacion (inicial)
max_steps: 500  # numero maximo de pasos por simulacion (final)
poblacion: 500  # individuos por poblacion
generaciones: 1000  # generaciones
progenitores: 50  # progenitores por generacion
mutacion: 0.05  # probabilidad de mutacion
max_reps: 9  # maximo numero de veces que puede repetir posicion hasta early-stopping
