# ESCENARIO
w_w: 300  # ancho
w_h: 300  # alto
obj_r: 25  # radio del objetivo
# OVEJAS
N: 50  # numero de ovejas
r_s: 65.0  # radio de repulsion del pastor
r_a: 2.0  # radio de repulsion de otras ovejas
h: 0.5  # coeficiente de inercia
c: 1.05  # coeficiente de cohesion
rho_a: 2.0  # fuerza de repulsion (oveja-oveja)
rho_s: 1.0  # fuerza de repulsion (pastor-oveja)
e: 0.3  # ruido angular (componente estocastica)
delta: 1.0  # distancia por paso
n_neigh: 7  # numero de vecinos para cohesion
r_walk: 0.05  # probabilidad de random walk
# PASTOR
p_delta: 1.5  # distancia por paso
model: "NN"  # modelo de comportamiento del pastor (followMouse | NN)
min_w: -7  # valor minimo de peso
max_w: 8  # valor maximo de peso
pers_ovejas: 5  # ovejas percibidas por el pastor
pers_pastores: 0  # otros pastores percibidos por el pastor
hidden_lay_1: 8  # neuronas de la primer capa oculta
hidden_lay_2: 4  # neuronas de la segunda capa oculta
# ENTRENAMIENTO
max_steps: 2000  # numero maximo de pasos por simulacion
poblacion: 500  # individuos por poblacion
generaciones: 1000  # generaciones
progenitores: 50  # progenitores por generacion
mutacion: 0.05  # probabilidad de mutacion
